### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cciollaro** [vgmoose/urwiddu#2]
pls fix this error

```
Traceback (most recent call last):
  File "browse.py", line 517, in <module>
    main()
  File "browse.py", line 416, in main
    DirectoryBrowser().main()
  File "browse.py", line 403, in main
    self.loop.run()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python2.7/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python2.7/site-packages/urwid/treetools.py", line 419, in keypress
    key = self.__super.keypress(size, key)
  File "/usr/local/lib/python2.7/site-packages/urwid/listbox.py", line 1001, in keypress
    return actual_key(self._keypress_down((maxcol, maxrow)))
  File "/usr/local/lib/python2.7/site-packages/urwid/listbox.py", line 1119, in _keypress_down
    widget, pos = self.body.get_next(pos)
  File "/usr/local/lib/python2.7/site-packages/urwid/treetools.py", line 399, in get_next
    target = widget.next_inorder()
  File "/usr/local/lib/python2.7/site-packages/urwid/treetools.py", line 108, in next_inorder
    nextnode = thisnode.next_sibling()
  File "/usr/local/lib/python2.7/site-packages/urwid/treetools.py", line 262, in next_sibling
    return self.get_parent().next_child(self.get_key())
  File "/usr/local/lib/python2.7/site-packages/urwid/treetools.py", line 337, in next_child
    index = self.get_child_index(key)
  File "/usr/local/lib/python2.7/site-packages/urwid/treetools.py", line 332, in get_child_index
    str(self.get_child_keys())))
urwid.treetools.TreeWidgetError: Can't find key Users in ParentNode None
ParentNode items: [None]
```

**Comment by vgmoose** [comment]
see #5
